### ISSUE TITLE
Basic file

### ISSUE THREAD

**Issue by minhkhoinguy** [NJscc/group_project_one#7]
User Story: 
AS someone who loves to watch movies.  
I WANT a  page to exist.  
SO THAT I can search for movies and foods that match my taste.  

Acceptance Criteria:
- [x] 'index.html'exists
- [x] 'style.css'exists
- [x] 'script.js'exists

**Comment by KVPang** [comment]
- [ ] index.html 
- [ ] style.css
- [ ] script.js 

There should be an Assets folder in the project file, and only the ReadME and index.html should be in the main folder - style.css should be in a folder within Assets called css and script.js should be within a folder called js inside the Assets folder.
